question_data = [
    {"text": "Python is a case-sensitive language.", "answer": "True"},
    {"text": "Python is a compiled language.", "answer": "False"},
    {"text": "Python uses indentation to define code blocks.", "answer": "True"},
    {"text": "In Python, variables must be declared with their data type.", "answer": "False"},
    {"text": "Python supports object-oriented programming.", "answer": "True"},
    {"text": "The 'def' keyword is used to define a function in Python.", "answer": "True"},
    {"text": "In Python, lists are immutable.", "answer": "False"},
    {"text": "The 'print()' function is used to display output in Python.", "answer": "True"},
    {"text": "Python is a low-level programming language.", "answer": "False"},
    {"text": "Python supports multiple inheritance.", "answer": "True"},
    {"text": "In UI/UX design, wireframes are used to represent the final visual design.", "answer": "False"},
    {"text": "Usability testing is a method to evaluate how easy a user interface is to use.", "answer": "True"},
    {"text": "A design system ensures consistency across a product's UI.", "answer": "True"},
    {"text": "Event propagation in web development refers to the way events travel through the DOM.", "answer": "True"},
    {"text": "In CSS, the 'float' property is used to center elements horizontally.", "answer": "False"},
    {"text": "Prototyping helps in testing design concepts before full-scale development.", "answer": "True"},
    {"text": "In UI design, 'padding' refers to the space outside an element's border.", "answer": "False"},
    {"text": "Responsive design ensures that a website looks good on all devices.", "answer": "True"},
    {"text": "In UX design, 'persona' refers to a fictional character representing a user type.", "answer": "True"},
    {"text": "In DaVinci Resolve, trimming clips is slower than re-editing them.", "answer": "False"},
    {"text": "The free version of DaVinci Resolve supports UHD (3840x2160) projects.", "answer": "False"},
    {"text": "DaVinci Resolve has a feature called 'Color Wheels' for color correction.", "answer": "True"},
    {"text": "In DaVinci Resolve, the 'Inspector' panel allows access to clip parameters.", "answer": "True"},
    {"text": "DaVinci Resolve's 'Fairlight' page is used for video editing.", "answer": "False"},
    {"text": "DaVinci Resolve supports keyframe animation for effects.", "answer": "True"},
    {"text": "In DaVinci Resolve, a 'subclip' duplicates media on your hard drive.", "answer": "False"},
    {"text": "DaVinci Resolve's 'Cut' page is designed for quick editing tasks.", "answer": "True"},
    {"text": "In DaVinci Resolve, the 'FX' icon indicates an effect has been applied to a clip.", "answer": "True"},
    {"text": "DaVinci Resolve supports multi-camera editing.", "answer": "True"},
    {"text": "In Blender, pressing the 'Tab' key switches between Object and Edit modes.", "answer": "True"},
    {"text": "Blender uses the Java programming language for scripting.", "answer": "False"},
    {"text": "In Blender, the 'E' key is used to extrude selected geometry.", "answer": "True"},
    {"text": "Blender's 'Cycles' is a real-time rendering engine.", "answer": "False"},
    {"text": "In Blender, 'vertices' are points in 3D space that define the shape of a mesh.", "answer": "True"},
    {"text": "Blender cannot be used for video editing.", "answer": "False"},
    {"text": "The 'S' key in Blender is used to scale selected objects.", "answer": "True"},
    {"text": "Blender supports both CPU and GPU rendering.", "answer": "True"},
    {"text": "In Blender, modifiers are used to permanently change the geometry of an object.", "answer": "False"},
    {"text": "Blender is available only for Windows operating systems.", "answer": "False"},
    {"text": "In Blender, the 'R' key is used to rotate selected objects.", "answer": "True"},
    {"text": "Python's '==' operator is used to assign values to variables.", "answer": "False"},
    {"text": "In UI/UX design, 'accessibility' ensures that products are usable by people with disabilities.", "answer": "True"},
    {"text": "In CSS, 'margin' refers to the space inside an element's border.", "answer": "False"},
    {"text": "In DaVinci Resolve, the 'Media Pool' is used to organize project assets.", "answer": "True"},
    {"text": "Blender's 'Grease Pencil' tool is used for 3D modeling.", "answer": "False"},
    {"text": "In Python, the '#' symbol is used to denote comments.", "answer": "True"},
    {"text": "In UI design, 'hierarchy' helps users understand the importance of elements.", "answer": "True"},
    {"text": "DaVinci Resolve's 'Fusion' page is used for audio editing.", "answer": "False"},
    {"text": "In Blender, 'NURBS' stands for Non-Uniform Rational B-Splines.", "answer": "True"},
    {"text": "Python supports both procedural and object-oriented programming paradigms.", "answer": "True"},
    {"text": "In UI/UX, a 'prototype' is a final version of the product.", "answer": "False"}
]
