from art import text2art
from random import randint

EASY_LEVEL_TURNS = 10
HARD_LEVEL_TURS = 5

def check_answer(user_guess, actual_answer, turns):
    """Checks answer against guess, returns the number of turns remaining

    Args:
        user_guess (int): user randomly guesses a number between 1 to 100
        actual_answer (int): correct answer generated by computer
        turns (int): number of attempts left to guess

    Returns:
        int: number of attempts left to guess
    """
    if user_guess > actual_answer:
        print("Too high")
        return turns - 1
    elif user_guess < actual_answer:
        print("Too low")
        return turns - 1
    else:
        print(f"You got it! The answer was {actual_answer}")
    
def set_level():
    """differnt levels to play the game

    Returns:
        str: returns current level
    """
    level = input("Choose a difficulty 'easy' or 'hard': ").lower()
    if level == 'easy':
        return EASY_LEVEL_TURNS
    else:
        return HARD_LEVEL_TURS

def game():
    """Main function to start the game"""
    print(text2art("Number Guessing Game"))
    print("Welcome to the Number Guessing Game!")
    print("I'm thinking of number between 1 and 100.")
    
    answer = randint(1, 100)
    # print(f"Psst, the correct answer is {answer}")

    turns = set_level()

    guess = 0
    while guess != answer:
        print(f"You got {turns} attempts remaining to guess the number.")
        
        guess = int(input("Make a Guess: "))
        turns = check_answer(guess, answer, turns)
        if turns == 0:
            print(f"You have run out of guesses, You Lose!")
            return
        elif guess != answer:
            print("Guess Again!!")


if __name__ == "__main__":
    game()
